server:
  port: 8918

spring:
 application:
   name: client-2


eureka:
   client:
      serviceUrl:
           defaultZone: http://127.0.0.1:8171/eureka/

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000